import type { Metadata } from "next";
import Image from "next/image";
import { FinalCta, PageIntro } from "../components/Shared";

export const metadata: Metadata = {
  title: "About Louise Hendey | BACP Registered Counsellor",
  description: "Meet Louise Hendey, a warm, client-led counsellor, BACP Registered Member and NCPS Accredited practitioner working in Mottingham and online.",
  alternates: { canonical: "/about-louise/" },
};

export default function AboutLouise() {
  return <main id="main-content">
    <PageIntro eyebrow="About Louise" title="Finding the right counsellor is personal"><p>My name is Louise. Like many people, I have dealt with challenges and setbacks in my own life. Therapy was transformative for me and changed my life for the better. My own experience led me to realise that I wanted to offer something similar to others: a warm, relational space where you can feel heard, understood and supported without judgement.</p></PageIntro>
    <section className="section section-white"><div className="container split-grid"><Image className="room-feature landscape-photo" src="/images/louise-hendey-seated-therapy-room.webp" alt="Louise Hendey seated in her private therapy room" width={1616} height={1080} sizes="(max-width: 980px) 92vw, 45vw"/><div className="copy-stack"><p className="eyebrow">Working together</p><h2>What it is like to work with me</h2><p>The therapy hour belongs to you. We will work together at a pace that feels manageable, checking that the focus remains useful and that you feel involved in the process. I aim to be warm, open and honest in my work, and to help you leave sessions feeling as grounded as possible.</p><p>I respect that every person is different. I will not try to fit you into a formula. Our work will be shaped around your experiences, your needs and what you hope to understand or change.</p></div></div></section>
    <section className="section"><div className="container narrow"><div className="section-heading"><p className="eyebrow">Professional experience</p><h2>Experience</h2><p>I have spent many years working with children and families. Alongside my private practice, I work as a counsellor for Mind. I have also spent many years moderating an online support community relating to sexual abuse.</p></div></div></section>
    <section className="section section-sage"><div className="container"><div className="section-heading"><p className="eyebrow">Training and trust</p><h2>Qualifications and professional membership</h2></div><div className="credentials-grid"><ul className="qualification-list"><li>Advanced Diploma in Counselling and Therapy</li><li>Diploma in Counselling Skills</li><li>Certificate in Counselling Skills</li><li>Certificate in Online and Telephone Counselling</li><li>BACP Registered Member MBACP 419515</li><li>NCPS Accredited member</li><li>Ongoing continuing professional development, with particular interests including trauma, the brain, recovery from sexual abuse and inner-child work</li></ul><div className="credential-card"><Image src="/images/bacp-registered-member-419515.png" alt="BACP Registered Member 419515 MBACP, Professional Standards Authority accredited register" width={748} height={250}/><a href="https://www.bacp.co.uk/therapists/419515/louise-hendey/mottingham-se9" target="_blank" rel="noreferrer">View Louise on the BACP register →</a><strong>NCPS Accredited</strong><p>Public NCPS profile link to be added once Louise confirms the exact URL.</p></div></div></div></section>
    <section className="section section-white"><div className="container split-grid reverse"><Image className="room-feature landscape-photo" src="/images/louise-hendey-therapy-room-empty.webp" alt="Louise Hendey's private therapy room with a green chair, yellow chair and small table" width={1616} height={1080} sizes="(max-width: 980px) 92vw, 45vw"/><div className="copy-stack"><p className="eyebrow">Face-to-face sessions</p><h2>The therapy setting</h2><p>Face-to-face sessions take place by appointment in a comfortable, purpose-built therapy room in the Mottingham area. The room is heated and air-conditioned. For privacy and safety, the full address and travel information are provided once an appointment has been arranged.</p></div></div></section>
    <FinalCta title="Would you like to see whether working together feels right?">The free introductory call is a chance to ask questions without any obligation to book.</FinalCta>
  </main>;
}
