import Image from "next/image";
import Link from "next/link";
import { ServiceIcon, SessionIcon } from "./components/Shared";

const services = [
  { title: "Trauma and difficult past experiences", body: "Gentle, paced work around experiences that still affect how you feel, relate or respond today.", icon: 1 },
  { title: "Anxiety and overwhelm", body: "Space to understand what is driving the worry, pressure or sense of being unable to switch off.", icon: 0 },
  { title: "Self-esteem and confidence", body: "Explore the critical voice, self-doubt and patterns that make it hard to value yourself.", icon: 2 },
  { title: "Relationships and boundaries", body: "Look at repeated relationship patterns, communication, conflict, people-pleasing and boundaries.", icon: 3 },
  { title: "Bereavement and loss", body: "A compassionate space for grief, change, endings and losses that may not always be understood by others.", icon: 4 },
  { title: "Women’s issues and life transitions", body: "Support through identity, body image, caring roles, menopause, fertility, pregnancy-related experiences and major life changes.", icon: 5 },
];
const previewFaqs = [
  ["What happens in the first session?","We will begin with what has brought you to counselling, what you hope for and any questions or concerns you have. You do not need to arrive with a perfectly organised story."],
  ["What if I feel nervous?","That is completely understandable. Starting therapy with someone new can feel daunting. You are welcome to say that you feel nervous, and we can begin gently."],
  ["Is counselling confidential?","What you share is treated confidentially. There are limited legal and safeguarding exceptions, which I will explain clearly when we begin working together."],
];

export default function Home() {
  return <main id="main-content">
    <section className="hero"><div className="container hero-grid">
      <div className="hero-copy"><p className="eyebrow">Louise Hendey Counselling and Therapy</p><h1>A calm place to talk when life feels difficult</h1>
        <div className="lead"><p>You may be feeling anxious, overwhelmed, low, stuck in patterns that no longer help, or affected by experiences from the past. You do not need to have everything worked out before getting in touch.</p><p>I offer warm, confidential counselling for adults, face to face by appointment in the Mottingham and South East London area, and online across the UK.</p></div>
        <div className="button-row"><Link className="button button-primary" href="/contact/#free-call">Book a free 15-minute call</Link><a className="button button-outline" href="tel:+447909578954">Call Louise: 07909 578954</a></div>
        <p className="microcopy">No obligation - simply a chance to ask questions and see whether working together feels right.</p>
      </div>
      <div className="hero-images hero-images-landscape"><Image className="room-hero landscape-photo" src="/images/louise-hendey-therapy-room-empty.webp" alt="Louise Hendey's private therapy room with a green chair, yellow chair and small table" width={1616} height={1080} priority sizes="(max-width: 980px) 90vw, 42vw" /><Image className="portrait-card" src="/images/louise-hendey-headshot-front.webp" alt="Louise Hendey smiling" width={1080} height={1616} priority sizes="190px" /><p className="hero-caption">A private, purpose-built room in the Mottingham area</p></div>
    </div></section>
    <section className="trust-strip" aria-label="Key practice information"><div className="trust-grid"><div className="trust-item"><strong>BACP Registered Member MBACP 419515</strong></div><div className="trust-item"><strong>NCPS Accredited</strong></div><div className="trust-item"><strong>£60 per one-hour session</strong></div><div className="trust-item"><strong>Online and face-to-face</strong></div></div></section>
    <section className="section"><div className="container"><div className="section-heading"><p className="eyebrow">How I can help</p><h2>What would you like support with?</h2><p>People come to counselling for many different reasons. You may recognise one of these, several of them, or simply know that something does not feel right.</p></div>
      <div className="service-grid">{services.map(s=><article className="service-card" key={s.title}><ServiceIcon type={s.icon}/><h3>{s.title}</h3><p>{s.body}</p></article>)}</div>
      <div className="button-row"><Link className="text-link" href="/how-i-can-help/">See how I can help →</Link></div>
    </div></section>
    <section className="section section-sage"><div className="container"><div className="section-heading"><p className="eyebrow">Ways to work together</p><h2>Counselling that fits around you</h2></div><div className="options-grid"><article className="option-card"><SessionIcon type="room"/><h3>Face-to-face counselling</h3><p>Sessions are available by appointment in a comfortable, private therapy room in the Mottingham area. Full address and travel details are shared once an appointment is arranged.</p></article><article className="option-card"><SessionIcon type="online"/><h3>Online counselling</h3><p>Meet from a private place that works for you, using a secure video call. Online counselling is available across the UK.</p></article></div><div className="button-row"><Link className="button button-primary" href="/contact/">Ask about availability</Link></div></div></section>
    <section className="section section-white"><div className="container split-grid"><Image className="portrait-feature" src="/images/louise-hendey-portrait-angled.webp" alt="Louise Hendey smiling against a black background" width={1080} height={1616} sizes="(max-width: 980px) 92vw, 45vw"/><div className="copy-stack"><p className="eyebrow">About Louise</p><h2>Hello, I’m Louise</h2><p>Like many people, I have experienced challenges and setbacks in my own life. Therapy was transformative for me and helped me recognise that I wanted to offer others the same kind of warm, relational support.</p><p>I work in a client-led way, putting you and your needs at the centre of our work. I believe that a trusting therapeutic relationship can give you the safety to understand yourself more clearly and begin to make life feel more manageable.</p><div className="button-row"><Link className="button button-outline" href="/about-louise/">More about Louise</Link></div></div></div></section>
    <section className="section"><div className="container"><div className="section-heading"><p className="eyebrow">Your first steps</p><h2>Starting counselling can be simple</h2></div><div className="steps-grid"><article className="step-card"><span className="step-number">01</span><h3>Get in touch</h3><p>Call, email or send a short message. You do not need to explain everything at this stage.</p></article><article className="step-card"><span className="step-number">02</span><h3>Free 15-minute Zoom call</h3><p>Contact me to arrange a time, or book directly through my Counselling Directory profile.</p></article><article className="step-card"><span className="step-number">03</span><h3>First session</h3><p>We begin gently with what has brought you to counselling and what you would like from the time.</p></article></div></div></section>
    <section className="section section-white"><div className="container"><div className="fee-band"><div><p className="eyebrow light">Fees</p><h2>Clear and straightforward fees</h2><p>Counselling sessions are £60 and last one hour. A free 15-minute introductory Zoom call is available before you decide whether to book.</p></div><Link className="button button-light" href="/fees-and-questions/">View fees and common questions</Link></div></div></section>
    <section className="section"><div className="container narrow"><div className="section-heading"><p className="eyebrow">Before you begin</p><h2>Questions people often ask</h2></div><div className="faq-preview">{previewFaqs.map(f=><details key={f[0]}><summary>{f[0]}</summary><p>{f[1]}</p></details>)}</div><div className="button-row"><Link className="text-link" href="/fees-and-questions/">Read all common questions →</Link></div></div></section>
    <section className="final-cta"><div className="container"><p className="eyebrow light">A gentle first step</p><h2>You do not have to decide everything today</h2><p>A free 15-minute Zoom call is simply a chance to ask questions and see whether taking the next step feels right.</p><div className="button-row centered"><Link className="button button-light" href="/contact/#free-call">Book a free 15-minute call</Link><a className="button button-ghost-light" href="tel:+447909578954">Call 07909 578954</a></div></div></section>
  </main>;
}
